# .goreleaser.yml
project_name: dtm
builds:
  - env: [CGO_ENABLED=0]
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
    id: 'dtm'
    dir: .
    main: main.go
    ldflags:
      - -s -w -X main.Version={{.Version}} -X main.Commit={{.Commit}} -X main.Date={{.Date}}
brews:
  - homepage: 'https://d.dtm.pub'
    description: 'A cross-language distributed transaction manager.'
    folder: Formula
    commit_author:
      name: yedf2
      email: 120050102@qq.com
    tap:
      owner: yedf2
      name: dtm
