language: go
go:
  - 1.15.x
env:
  - GO111MODULE=on
services:
  - mysql
before_install:
  - go get -t -v ./...
  - go get github.com/mattn/goveralls
script:
  - $GOPATH/bin/goveralls -service=travis-ci
