language: go
go:
  - 1.15.x
env:
  - GO111MODULE=on
branches:
  only:
    - master
    - main
    - alpha
services:
  - mysql
  - redis-server
before_install:
  - go get -t -v ./...
  - go get github.com/yedf2/goveralls
script:
  - $GOPATH/bin/goveralls -envs=TEST_STORE=redis,TEST_STORE=mysql,TEST_STORE= -service=travis-ci -ignore="examples/*,dtmgrpc/dtmgimp/*.pb.go,bench/*,test/*"
