language: go
go:
  - 1.15.x
env:
  - GO111MODULE=on
before_script:
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('my-secret-pw') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
script: go test ./...
